# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

  precision: 2
  round: down
  range: "50...100"

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  behavior: default
  require_changes: false

ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "src/test/**"
  - "src/main.tsx"
  - "dist/**"
  - "node_modules/**"
